export default function ConversationDrawer() {
  return (
    <div className="fixed left-0 flex h-full w-64 flex-grow flex-col overflow-y-scroll border-r bg-base-200">
      <div className="navbar min-h-8 sticky top-0 z-10 h-10 justify-center bg-base-200">
        Conversations
      </div>
      <p>1.</p>
      <p>2.</p>
      <p>3.</p>
      <p>4.</p>
      <p>5.</p>
      <p>6.</p>
      <p>7.</p>
      <p>1.</p>
      <p>2.</p>
      <p>3.</p>
      <p>4.</p>
      <p>5.</p>
      <p>6.</p>
      <p>7.</p>
      <p>1.</p>
      <p>2.</p>
      <p>3.</p>
      <p>4.</p>
      <p>5.</p>
      <p>6.</p>
      <p>7.</p>
      <p>1.</p>
      <p>2.</p>
      <p>3.</p>
      <p>4.</p>
      <p>5.</p>
      <p>6.</p>
      <p>7.</p>
      <p>1.</p>
      <p>2.</p>
      <p>3.</p>
      <p>4.</p>
      <p>5.</p>
      <p>6.</p>
      <p>7.</p>
      <p>1.</p>
      <p>2.</p>
      <p>3.</p>
      <p>4.</p>
      <p>5.</p>
      <p>6.</p>
      <p>7.</p>
      <p>1.</p>
      <p>2.</p>
      <p>3.</p>
      <p>4.</p>
      <p>5.</p>
      <p>6.</p>
      <p>7.</p>
    </div>
  );
}
